=== artemtsushko/tariffs-xml-parser-validator/sample-data/tariffs.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT tariffs (tariff*)>
<!ELEMENT tariff (tariffName,operator,payroll,callPrices,smsPrice,parameters)>
<!ELEMENT tariffName (#PCDATA)>
<!ELEMENT operator (#PCDATA)>
<!ELEMENT payroll (#PCDATA)>
<!ELEMENT callPrices (withinNetwork,toOtherNetworks,toFixedLineNumbers)>
<!ELEMENT withinNetwork (#PCDATA)>
<!ELEMENT toOtherNetworks (#PCDATA)>
<!ELEMENT toFixedLineNumbers (#PCDATA)>
<!ELEMENT smsPrice (#PCDATA)>
<!ELEMENT parameters (favoiriteNumbers,pricing,subscribeFee)>
<!ELEMENT favoiriteNumbers (#PCDATA)>
<!ELEMENT pricing EMPTY>
<!ELEMENT subscribeFee (#PCDATA)>

<!ATTLIST tariff id ID #REQUIRED>
<!ATTLIST pricing unit (second|minute) #REQUIRED>

=== artemtsushko/tariffs-xml-parser-validator/sample-data/tariffs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tariffs SYSTEM "tariffs.dtd">

<tariffs>

	<tariff id="ks1">
		<tariffName>For Smartphone</tariffName>
		<operator>Kyivstar</operator>
		<payroll>50</payroll>
		<callPrices>
			<withinNetwork>0</withinNetwork>
			<toOtherNetworks>0.60</toOtherNetworks>
			<toFixedLineNumbers>1.50</toFixedLineNumbers>
		</callPrices>
		<smsPrice>0.50</smsPrice>
		<parameters>
			<favoiriteNumbers>0</favoiriteNumbers>
			<pricing unit="second"/>
			<subscribeFee>20</subscribeFee>
		</parameters>
	</tariff>

	<tariff id="ks2">
		<tariffName>For Smartphone+</tariffName>
		<operator>Kyivstar</operator>
		<payroll>95</payroll>
		<callPrices>
			<withinNetwork>0</withinNetwork>
			<toOtherNetworks>0</toOtherNetworks>
			<toFixedLineNumbers>1.50</toFixedLineNumbers>
		</callPrices>
		<smsPrice>0.50</smsPrice>
		<parameters>
			<favoiriteNumbers>0</favoiriteNumbers>
			<pricing unit="second"/>
			<subscribeFee>20</subscribeFee>
		</parameters>
	</tariff>

	<tariff id="ks3">
		<tariffName>For Smartphone Extra</tariffName>
		<operator>Kyivstar</operator>
		<payroll>150</payroll>
		<callPrices>
			<withinNetwork>0</withinNetwork>
			<toOtherNetworks>0</toOtherNetworks>
			<toFixedLineNumbers>1.50</toFixedLineNumbers>
		</callPrices>
		<smsPrice>0</smsPrice>
		<parameters>
			<favoiriteNumbers>0</favoiriteNumbers>
			<pricing unit="second"/>
			<subscribeFee>0</subscribeFee>
		</parameters>
	</tariff>

	<tariff id="mts1">
		<tariffName>Just Super First</tariffName>
		<operator>MTS</operator>
		<payroll>0</payroll>
		<callPrices>
			<withinNetwork>0</withinNetwork>
			<toOtherNetworks>0.50</toOtherNetworks>
			<toFixedLineNumbers>1.50</toFixedLineNumbers>
		</callPrices>
		<smsPrice>1</smsPrice>
		<parameters>
			<favoiriteNumbers>0</favoiriteNumbers>
			<pricing unit="minute"/>
			<subscribeFee>15</subscribeFee>
		</parameters>
	</tariff>

	<tariff id="mts2">
		<tariffName>Smartphone 3G First</tariffName>
		<operator>MTS</operator>
		<payroll>15</payroll>
		<callPrices>
			<withinNetwork>0</withinNetwork>
			<toOtherNetworks>0.35</toOtherNetworks>
			<toFixedLineNumbers>1.50</toFixedLineNumbers>
		</callPrices>
		<smsPrice>1</smsPrice>
		<parameters>
			<favoiriteNumbers>0</favoiriteNumbers>
			<pricing unit="minute"/>
			<subscribeFee>20</subscribeFee>
		</parameters>
	</tariff>

</tariffs>
